site_name: Computboy个人静态网站
site_url: https://Computboy.github.io/

theme:
  name: material   # material主题，对功能支持较好
  language: en   # 默认界面语言（按钮、提示等）

nav:  # 导航栏
  - Home: index.md

extra_css:
  - assets/css/extra.css

plugins:
  - search
  - i18n:
      default_language: en
      languages:
        - locale: en
          name: English
        - locale: zh
          name: 中文

extra:
  alternate:   # 切换按键
    - name: English
      link: /
      lang: en
    - name: 中文
      link: /zh/
      lang: zh